### API 1 
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

### API 2
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
### API 3
GET http://localhost:3000/user/tweets/feed/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 4
GET http://localhost:3000/user/following/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 5
GET http://localhost:3000/user/followers/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 6 /tweets/:tweetId/
GET http://localhost:3000/tweets/1/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 7 /tweets/:tweetId/likes/
GET http://localhost:3000/tweets/4/likes/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 8 /tweets/:tweetId/replies/
GET http://localhost:3000/tweets/:tweetId/replies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 9 
GET http://localhost:3000/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU

### API 10 /user/tweets/
POST http://localhost:3000/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

### API 11 /tweets/:tweetId/
DELETE http://localhost:3000/tweets/3/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2ODA4MjI4fQ.4lxK5M49QaYJI2diZZomcECTbOSnSXeNor2tN7Z2DKU
